### ISSUE TITLE
Private Key Generation

### ISSUE THREAD

**Issue by sos0** [norestlabs/knowledgr-frontend#108]
- Generate a Private Key for the user when they begin the registration process.
- At the end of the account creation process, show an additional screen that displays the Private Key for the user.
- Div structure for this page:

==========================
```
{ title: "Private Key" }
{ Disclaimer/warning text: "STOP. Do not lose this Private Key. Write it down somewhere or save it safely. You must use the Private Key to log into Knowledgr from now on. If you lose this private key, we **cannot** recover your account."}

{ Private Key goes here }

{ button: "Copy Private Key" } { button: "Continue" }
```
============================

- "Continue" button here leads to the main page.

**Comment by gedanziger** [comment]
Note that a Steem owner key should be used, and not a mnemonic. It is similar otherwise. 

References to Mnemonic should change to `Private Key`
