### ISSUE TITLE
js files not loading for some users

### ISSUE THREAD

**Issue by sos0** [norestlabs/knowledgr-frontend#165]
~May be a caching issue.~

### Bug Screenshot
![image](https://user-images.githubusercontent.com/1973082/54240810-620ca300-44dc-11e9-96f3-5e4281a07f23.png)

### Reproduction
- Must be in Thailand's time zone.
![image](https://user-images.githubusercontent.com/1973082/57681423-83753280-75e4-11e9-963c-05a890520c9f.png)

**Comment by sos0** [comment]
may be related to https://stackoverflow.com/questions/25993826/err-content-length-mismatch-on-nginx-and-proxy-on-chrome-when-loading-large-file

**Comment by oleg-baturov** [comment]
Need to check from Asia location. (ex: Indonesia)
Need to check `Content-Security-Policy` setting.

@Bring2Real
