### ISSUE TITLE
View Detail Node - Display Full Text

### ISSUE THREAD

**Issue by sos0** [norestlabs/knowledgr-frontend#183]
## Requirements
- Display the full text of the detail node with markdown or html format.
- Instead of "Introduction:", just display the full text.

http://knowledgrdemo.mousebelt.com:8080/knowledgr/@oleg/re-oleg-writing-a-philosophy-paper-20190613t022139696z

http://knowledgrdemo.mousebelt.com:8080/knowledgr/@oleg/re-oleg-this-is-how-to-write-an-effective-research-paper-20190613t032734041z

These link above should show 4 to 5 paragraphs of text and they use markdown.

**Comment by oleg-baturov** [comment]
Verified by 65ce64fb90d241c7ac3e0bc42d0f9f45ca17fe6a
