### ISSUE TITLE
Register Flow Design

### ISSUE THREAD

**Issue by sos0** [norestlabs/knowledgr-frontend#34]
Update register pages to use Knowledgr's design (it should look similar to login page.)

<img width="1235" alt="image" src="https://user-images.githubusercontent.com/1973082/51560441-63edaa80-1e39-11e9-9211-1b11315f9c26.png">

**Comment by oleg-baturov** [comment]
Verified by 8e13ee61c4c659d0a70b1ac9258c577b3958fba8
