### ISSUE TITLE
Only Search page should say "Search Results"

### ISSUE THREAD

**Issue by gedanziger** [norestlabs/knowledgr-frontend#43]
On the homepage, do not show the section "Search Results" If a user searches at the top, then the template should say "Search Results"

![screen shot 2019-01-24 at 3 42 53 pm](https://user-images.githubusercontent.com/5342263/51718395-e6bd6380-1ff9-11e9-9fed-d9138f1b383d.png)

On the home screen (no searches), this search results item should be gone.

**Comment by oleg-baturov** [comment]
Verified by 8e13ee61c4c659d0a70b1ac9258c577b3958fba8
