### ISSUE TITLE
Search Result Redesign

### ISSUE THREAD

**Issue by sos0** [norestlabs/knowledgr-frontend#57]
### Additions need to be made to a post’s search result
- Date added ✓
- Discipline Tag
- Kscore
- Combined # of O/Q/H’s that cite this post
- \# of reviews ✓
- Brief text summary of post ✓
- Nested comments (once expanded) max 3

**Comment by oleg-baturov** [comment]
Verified by 720afd062c9e3073bec6fbcec4ef8d473d2c4b47
