### ISSUE TITLE
UI Update: Navigation Bar Reorganization + Color Palette + Related Posts Removal...

### ISSUE THREAD

**Issue by sos0** [norestlabs/knowledgr-frontend#58]
## Navigation Bar Reorganization + Color Palette + Related Posts Removal...
- Update all references to colors as defined by the color palette below:
<img width="169" alt="image" src="https://user-images.githubusercontent.com/1973082/51875931-c05e3780-231b-11e9-98f5-f1876e416ab0.png">

- Change order of O/Q/H in header from `Questions -> Hypotheses -> Observations` to `Observations -> Questions -> Hypotheses`
- Add header O/Q/H buttons as defined by icons in the image above
- Remove `Related Posts` section from all `Search Results` pages.
- Remove `Browsing History` section from `Detail Post` page
- Remove box shadow outline complete from `Create New Post` page (See #55)

**Comment by oleg-baturov** [comment]
Verified by 9c4967cdbc7fbd23778df2a9744a1adf9f76e267
