### ISSUE TITLE
Node Detail View Page UI Updates

### ISSUE THREAD

**Issue by sos0** [norestlabs/knowledgr-frontend#59]
## Node Detail View Page UI Updates
- Remove Browsing History section
- Add this filter dropdown to the side panels 
<img width="144" alt="image" src="https://user-images.githubusercontent.com/1973082/51876533-b89f9280-231d-11e9-916b-3066f3dc5926.png">
- Change highlight menu to say (Ob/Qu/Hy) and if possible, add a <span> above that says 'Add new:' above the menu. So it should look something like:

```
[ Add new:           ]
[ {Ob} | {Qu} | {Hy} ]
```
<img width="690" alt="image" src="https://user-images.githubusercontent.com/1973082/51876556-ce14bc80-231d-11e9-939e-91ab305cdbc0.png">

Once the user clicks one of the `Ob, Qu, Hy`, it should lead to the next UI (See #60)

**Comment by oleg-baturov** [comment]
Verified by 720afd062c9e3073bec6fbcec4ef8d473d2c4b47
