### ISSUE TITLE
Highlight Routing

### ISSUE THREAD

**Issue by sos0** [norestlabs/knowledgr-frontend#60]
<img width="690" alt="image" src="https://user-images.githubusercontent.com/1973082/51876556-ce14bc80-231d-11e9-939e-91ab305cdbc0.png">

When the user clicks the create button (or the Ob | Qu | Hy in new design), instead of taking them to the create new node page, display the Create New Node page in the right side panel in this page instead. (So there is no routing them to a new page, they will just see the create new node page in this right side panel when it opens.)

Right side panel:
<img width="1102" alt="image" src="https://user-images.githubusercontent.com/1973082/51877068-97d83c80-231f-11e9-8891-ba5dc079f179.png">

Inside new right side panel:
<img width="832" alt="image" src="https://user-images.githubusercontent.com/1973082/51879101-f654e900-2326-11e9-8705-e621c68f219b.png">

At the top of new right side panel:
"

You highlighted:
`There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, , or randomised words which don't look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text.`

"

**Comment by oleg-baturov** [comment]
Verified by 720afd062c9e3073bec6fbcec4ef8d473d2c4b47
