### ISSUE TITLE
Detail Node Page: Review Section

### ISSUE THREAD

**Issue by sos0** [norestlabs/knowledgr-frontend#61]
## Detail Node Page: Review Section
- In this section next to Cites/Cited By, add "Review: { reviewCount }"
<img width="682" alt="image" src="https://user-images.githubusercontent.com/1973082/51877830-5eed9700-2322-11e9-9d34-09fdb606334f.png">

- Make the review count clickable. When the user clicks on it, open the right side panel and display a section to display the reviews of the post. It should look basically the same as the highlights panel, but the title should say Reviews.
<img width="1102" alt="image" src="https://user-images.githubusercontent.com/1973082/51877068-97d83c80-231f-11e9-8891-ba5dc079f179.png">

So the section should look like:
```
// No "Cited by Others" section
Top Reviews                  <Filter Dropdown (Sort by {Votes , K-power, Newest}) />
<Review (looks same as design above) />

**Comment by oleg-baturov** [comment]
Verified by 720afd062c9e3073bec6fbcec4ef8d473d2c4b47
