### ISSUE TITLE
Side Menu on Detail Node Page

### ISSUE THREAD

**Issue by sos0** [norestlabs/knowledgr-frontend#62]
<img width="522" alt="image" src="https://user-images.githubusercontent.com/1973082/51879192-40d66580-2327-11e9-9db4-06300ec1dcf8.png">

Replace the icons on the left side menu with:
- [ Qu+ ] Hover to say "Create New Question"
- [ Re+ ] Hover to say "Create New Review"
- [ Link Icon ] Hover to say "Share"
- [ Star Icon ] Hover to say "Bookmark"
<img width="169" alt="image" src="https://user-images.githubusercontent.com/1973082/51875931-c05e3780-231b-11e9-98f5-f1876e416ab0.png">

## Icon References:
https://feathericons.com/

### Share
<img width="169" alt="image" src="https://user-images.githubusercontent.com/1973082/51792595-3457de80-2168-11e9-998c-5a1455a8ed38.png">

### Star (Resteem)
<img width="165" alt="image" src="https://user-images.githubusercontent.com/1973082/51869293-fc39d280-2304-11e9-871d-c266ba8b3d6a.png">

**Comment by oleg-baturov** [comment]
Verified by 720afd062c9e3073bec6fbcec4ef8d473d2c4b47
