### ISSUE TITLE
Author Page

### ISSUE THREAD

**Issue by sos0** [norestlabs/knowledgr-frontend#63]
Entire author page currently missing. (No design)
When the user clicks on any author's username, redirect the user to the profile page for the user.

Show on left side author's posts (should basically look like search results page, but everything written by one author)

Show as a right panel the author information similar to this structure:
<img width="400" alt="image" src="https://user-images.githubusercontent.com/1973082/51885963-a7b54800-2342-11e9-84d6-07cc2d779a44.png">

### Top section
- User information (Avatar, public name, current title, k-power)
- Optional user biography (short paragraph. You can use text in the image for mock text.)
- Educational affiliation (current university + university title)
- Link to university profile
- Optional join date (can be removed)

### Mid section
- List of expertise + related k-power
- Remove section that says followers/following. Instead write # of Hypotheses, # of Questions, # of Observations

### Bottom section
- Remove bottom section that says "Subscriptions".

**Comment by oleg-baturov** [comment]
Verified by 4bc177b68cce124e2b25c5a4510adfd847efae7b
