### ISSUE TITLE
Expertise labels design update

### ISSUE THREAD

**Issue by sos0** [norestlabs/knowledgr-frontend#68]
<img width="276" alt="image" src="https://user-images.githubusercontent.com/1973082/52514128-26707780-2bc4-11e9-9e7f-b8a94a470357.png">

These labels are not very readable. Add CSS:
```
font-family: "Futura", sans-serif;
text-transform: uppercase;
font-size: 12px;
```

![image](https://user-images.githubusercontent.com/1973082/52514179-764f3e80-2bc4-11e9-9637-a879b34c87d8.png)

**Comment by oleg-baturov** [comment]
Verified by 4bc177b68cce124e2b25c5a4510adfd847efae7b
