### ISSUE TITLE
Votes design update

### ISSUE THREAD

**Issue by sos0** [norestlabs/knowledgr-frontend#69]
Add or replace the following CSS:
```
.Votes {
    font-size: 16px;
    > div {
         ~height: 12px;~ // remove
         margin: 2px 0;
    }
}
```

So that the final result should look like this:

![image](https://user-images.githubusercontent.com/1973082/52514261-fbd2ee80-2bc4-11e9-981d-67f57c5b1d24.png)

**Comment by oleg-baturov** [comment]
Verified by 4bc177b68cce124e2b25c5a4510adfd847efae7b
