### ISSUE TITLE
Highlight component update/bug

### ISSUE THREAD

**Issue by sos0** [norestlabs/knowledgr-frontend#71]
<img width="926" alt="image" src="https://user-images.githubusercontent.com/1973082/52514453-c5966e80-2bc6-11e9-914a-1b07df2c5297.png">

1. Can we show in "You highlighted:" what the user highlighted?
2. The black menu should disappear once the user clicks on one of the Ob/Qu/Hy buttons.

**Comment by oleg-baturov** [comment]
Verified by 4bc177b68cce124e2b25c5a4510adfd847efae7b
