### ISSUE TITLE
Node Detail Page design update

### ISSUE THREAD

**Issue by sos0** [norestlabs/knowledgr-frontend#72]
```
.NodeWrapper .UserInfoWrapper .Title .Votes {
    font-size: 16px;

    > div {
        ~height: 12px;~ // remove
    }
}

```

Update votes css so that it looks like this for final result:

![image](https://user-images.githubusercontent.com/1973082/52514565-c1b71c00-2bc7-11e9-89f9-2f91b2ff6766.png)

**Comment by oleg-baturov** [comment]
Verified by 4bc177b68cce124e2b25c5a4510adfd847efae7b
