### ISSUE TITLE
Chaining Node Detail Pages

### ISSUE THREAD

**Issue by sos0** [norestlabs/knowledgr-frontend#73]
Create navigateable Link to this section:
<img width="382" alt="image" src="https://user-images.githubusercontent.com/1973082/52514652-9d0f7400-2bc8-11e9-963b-383cef238c74.png">

When the user clicks on it, it should navigate to the originated post page.

**Comment by sos0** [comment]
@Bring2Real the user should be able to navigate multiple levels in the graph by clicking through the UI.

**Comment by oleg-baturov** [comment]
Verified by 4bc177b68cce124e2b25c5a4510adfd847efae7b
