### ISSUE TITLE
Detail Page: Create Post Panel: Steemit Editor

### ISSUE THREAD

**Issue by sos0** [norestlabs/knowledgr-frontend#75]
<img width="656" alt="image" src="https://user-images.githubusercontent.com/1973082/52892075-2502fa00-3144-11e9-8892-06a2e4f8360a.png">

The Editor should only show the necessary fields.

We should:
- Remove Question field at the top
- Remove Title field
- Replace placeholder "Write your story..." to say "Question"
- When the user clicks on the editor, the active state CSS should be the same as the Knowledgr inputs (It should have the blue outline):
<img width="640" alt="image" src="https://user-images.githubusercontent.com/1973082/52892101-60052d80-3144-11e9-86e2-709106736bf6.png">
- Remove Tags field
- Remove "Rewards: 50% SBD / 50% SP"
- Remove "Advanced Settings"

**Comment by oleg-baturov** [comment]
Verified by 4bc177b68cce124e2b25c5a4510adfd847efae7b
